{% set name = "vcf_from_snvphyl" %}
{% set version = "0.0.1" %}
{% set sha256 = "cbf59997571d051f3f1dd4c08cf144c74e7ca4620c4c8f8d1651e645f4756beb" %}
{% set py2neo = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ environ['VERSION'] or version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/COMBAT-TB/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ environ['SHA'] or sha256 }}

build:
  script_env:
    - SHA
    - VERSION
    - CONDA_BLD_PATH
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - py2neo {{ py2neo }}
    - pytest
    - pandas
    - tqdm
  run:
    - python
    - click
    - py2neo {{ py2neo }}
    - pandas
    - tqdm

test:
  imports:
    - snptools
  commands:
    - vcf_from_snvphyl --help 2>&1 |grep SNVPhyl >/dev/null
    - python3 -m pytest

about:
  home: https://github.com/COMBAT-TB/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Parses variant report from SNVPhyl and generates annotated (ala. SnpEff) VCF files, using COMBAT-TB eXplorer database for annotation'
