{% set name = "vcf_from_snvphyl" %}
{% set version = "0.0.1" %}
{% set sha256 = "fbb108d45f7b21d629d5554ffbeff09be22f11e0828fb2d357273ee3d732c9aa" %}
{% set py2neo = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ environ['VERSION'] or version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/COMBAT-TB/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ environ['SHA'] or sha256 }}

build:
  script_env:
    - SHA
    - VERSION
    - CONDA_BLD_PATH
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - py2neo {{ py2neo }}
    - pandas
    - tqdm
  run:
    - python
    - click
    - py2neo {{ py2neo }}
    - pandas
    - tqdm

test:
  imports:
    - snptools
  commands:
    - vcf_from_snvphyl --help 2>&1 |grep SNVPhyl >/dev/null

about:
  home: https://github.com/COMBAT-TB/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Generate a report on M. tuberculosis variants with links to Combat TB Explorer database'
