{% set name = "vcf_from_snvphyl" %}
{% set version = "0.0.1" %}
{% set sha256 = "7fd11d76f604f0458570350f2ea50191bc9392cf09c0ba82d7057c75b81932f1" %}
{% set py2neo = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/COMBAT-TB/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  script_env:
    - DATABASE_URI
  build:
    - python
    - pip
    - biopython
    - intervaltree
    - py2neo {{ py2neo }}
    - pytest
    - pytest-runner
    - pandas
    - tqdm
  run:
    - python
    - biopython
    - intervaltree
    - py2neo {{ py2neo }}
    - pandas
    - tqdm

test:
  requires:
    - pytest
  imports:
    - snptools
  commands:
    - vcf_from_snvphyl  --help |grep SNVPhyl >/dev/null
    - pytest --pyargs snptools

about:
  home: https://github.com/COMBAT-TB/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Parses variant report from SNVPhyl and generates annotated (ala. SnpEff) VCF files, using COMBAT-TB eXplorer database for annotation'
